name: Emcala Developments
favicon: null
layout_spectrum: 0.85873
typography_spectrum: 0.40855219890363514
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#0063e2'
    - '#000106'
    - '#955d06'
    - '#afd8bc'
    - '#b69458'
  brandStrength: 0.0625
  lightness: 0.921175348572433
  saturation: 0.7892387944739312
  rhythmicContrast: 0.07657474395819008
purpose: []
