name: Emcala Developments
favicon: null
layout_spectrum: 0.6703530659433454
typography_spectrum: 0.40855219890363514
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#FF6700'
    - '#EBEBEB'
    - '#C0C0C0'
    - '#3A6EA5'
    - '#004E98'
  brandStrength: 0.13932088622823358
  lightness: 0.921175348572433
  saturation: 0.7892387944739312
  rhythmicContrast: 0.07657474395819008
purpose: []
